---
title: Make a personal Website with R
author: R package build
date: '2022-05-24'
slug: []
categories: []
tags: []
---

Having a personal website is so cool and it is too slow to update a blog on other websites such as Sina Blog.And These are the two main reasons for me to create my personal blog website.

Tool:

1.RStudio: RStudio is a development environment base on R where we make changes to code 

2.Hugo: This is a website for people to create web layouts and there are many different themes so we don’t have to write the source code for the web layout by ourselves. 

3.GitHub: When we made changes, we want to be able to track them. And that’s why need GitHub, a version control system. 

4.Netlify: a website can create a domain name and host the website like creating a road to tell people how to go to your house. When Github gets informed of the change we made, it will also inform the website held by Netlify.

Steps: 

1.Download the blogdown package in your Rstudio. The blogdown package is a manual written by YiHui Xie to tell R how to create a website. 

2.install Hugo and your selected theme from Hugo in Rstudio.

3.Create a repository with GitHub used to relate to your code file. Once you made something changes you can just upload it to GitHub.

4.Deploy the network with Netlify using the repository on GitHub 

5.Modify and write your website content in RStudio


We can also combine any type of file on the website. For example, I put a png file, a word document file, and a URL of my Google site. Among them, static files such as pictures and documents need to be placed in the corresponding folder. I got stuck in this step for a long time and couldn’t find the corresponding folder.Fortunately, static files are usually kept in one folder, so we may put all our static files into that folder. 

References:
https://bookdown.org/yihui/blogdown/